<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="17316" started-at="2017-10-27T20:30:52Z" finished-at="2017-10-27T20:31:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17316" started-at="2017-10-27T20:30:52Z" finished-at="2017-10-27T20:31:10Z">
      <class name="DataProviderExcel.ReadExcelDataProvider">
        <test-method status="PASS" signature="testSetup()[pri:0, instance:DataProviderExcel.ReadExcelDataProvider@1794d431]" name="testSetup" is-config="true" duration-ms="17191" started-at="2017-10-27T15:30:52Z" finished-at="2017-10-27T15:31:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetup -->
        <test-method status="FAIL" signature="VerifyInvalidLogin(java.lang.String, java.lang.String)[pri:0, instance:DataProviderExcel.ReadExcelDataProvider@1794d431]" name="VerifyInvalidLogin" duration-ms="0" started-at="2017-10-27T15:31:10Z" data-provider="empLogin" finished-at="2017-10-27T15:31:10Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Data Provider public java.lang.Object[][] DataProviderExcel.ReadExcelDataProvider.loginData() must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not class [[Ljava.lang.Object;]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Data Provider public java.lang.Object[][] DataProviderExcel.ReadExcelDataProvider.loginData() must return either Object[][] or Object[] or Iterator<Object[]> or Iterator<Object>, not class [[Ljava.lang.Object;
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:612)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1316)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1044)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1134)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyInvalidLogin -->
      </class> <!-- DataProviderExcel.ReadExcelDataProvider -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
